# This file extends the base Docker Compose files to make manual testing easy.
#
# Run the following to get started:
#
#     docker compose up -d
#
# That will start up services in the background. To take them down, you have to
# run:
#
#     docker compose down
#
# If you changed DB init scripts, then you should also run:
#
#     docker compose down -v
#
# That'll delete the volumes. Otherwise e.g. PostgreSQL will skip initializing
# if a DB already exists.
#
# If you omit `-d`, it'll run them all in the foreground, then you can stop them
# with your usual Ctrl-C terminal command.
#
# Facts:
#
# * The SERVICE PORTS numbering start at 32123, 32122 etc. to avoid other
#   existing instances of databases.
#
# * The login credentials are, where possible, all "aigent" to avoid unnecessary
#   mental overhead.

version: "3.6"
services:
  postgres:
    image: postgres
    restart: always
    env_file:
      - .env
    ports:
      - 45432:5432
    environment:
      POSTGRES_USER: "leaptable"
      POSTGRES_PASSWORD: "leaptable"
      POSTGRES_DB: "leaptable"
    volumes:
      - pgy-data:/var/lib/postgresql/data
      - ./docker/init.sql:/docker-entrypoint-initdb.d/init.sql

  redis:
    image: redis
    restart: always

  hasura:
    image: hasura/graphql-engine:v2.30.0
    restart: always
    environment:
      # postgres database to store Hasura metadata
      HASURA_GRAPHQL_METADATA_DATABASE_URL: postgres://leaptable:leaptable@postgres:5432/leaptable-gql
      # this env var can be used to add the above postgres database to Hasura as a data source.
      # this can be removed/updated based on your needs
      PG_DATABASE_URL: postgres://postgres:postgrespassword@postgres:5432/postgres
      ## enable the console served by server
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true" # set to "false" to disable console
      ## enable debugging mode. It is recommended to disable this in production
      HASURA_GRAPHQL_DEV_MODE: "true"
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
      # Set the admin secret. Change this to something more secure.
      HASURA_GRAPHQL_ADMIN_SECRET: "leaptable"
      # Unauthorized roles
      HASURA_GRAPHQL_UNAUTHORIZED_ROLE: "anonymous"
    depends_on:
      - postgres
    ports:
    - 48080:8080

  api:
      image: leaptable/api:latest
      restart: always
      command: [ "uvicorn", "leaptable.server.main:app", "--host", "0.0.0.0"]
      env_file:
        - .env.local
      ports:
        - 43000:8000

  studio:
    image: leaptable/studio:latest
    restart: always
    depends_on:
      - postgres
      - hasura
    env_file:
      - .env.local
    ports:
      - 43001:3000

  agent-browser:
    image: leaptable/engine:latest
    restart: always
    command: [ "python", "leaptable/agents/browser/main.py" ]
    depends_on:
      - redis
      - postgres
    environment:
      REDIS_STREAM_HOST: "redis"
      REDIS_CACHE_HOST: "redis"
    env_file:
      - .env.local

  agent-serpapi:
    image: leaptable/engine:latest
    restart: always
    command: [ "python", "leaptable/agents/serp/main.py" ]
    depends_on:
      - redis
      - postgres
    environment:
      REDIS_STREAM_HOST: "redis"
      REDIS_CACHE_HOST: "redis"
    env_file:
      - .env.local

  tool-browser:
    image: leaptable/engine:latest
    restart: always
    command: [ "python", "leaptable/tools/browser/main.py" ]
    depends_on:
      - redis
      - postgres
    environment:
      REDIS_STREAM_HOST: "redis"
      REDIS_CACHE_HOST: "redis"
    env_file:
      - .env.local
    deploy:
      mode: replicated
      replicas: 3

  tool-serpapi:
    image: leaptable/engine:latest
    restart: always
    command: [ "python", "leaptable/tools/serp/main.py" ]
    depends_on:
      - redis
      - postgres
    environment:
      REDIS_STREAM_HOST: "redis"
      REDIS_CACHE_HOST: "redis"
    env_file:
      - .env.local
    deploy:
      mode: replicated
      replicas: 3

volumes:
  pgy-data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /leap-data