# This file defined a development docker compose environment.
#
# Run the following to get started:
#
#   docker compose -f docker-compose.dev.yaml -p reframe up --remove-orphans
#
# That will start up services in the foreground. Press CTRL+C to exit.
#
# If you changed DB init scripts, then you should also run:
#
#     docker compose down -v
#
# That'll delete the volumes. Otherwise e.g. PostgreSQL will skip initializing
# if a DB already exists.
#
# If you omit `-d`, it'll run them all in the foreground, then you can stop them
# with your usual Ctrl-C terminal command.
#
# Facts:
#
# * The SERVICE PORTS numbering start at 45432, 48080, 43000, 43001 etc. to avoid other
#   existing instances of databases.
#
# * The login credentials are, where possible, all "reframe" to avoid unnecessary
#   mental overhead.

version: "3.6"
services:
  postgres:
    image: postgres
    restart: always
    tty: true
    env_file:
      - .env.dev
    ports:
      - 45432:5432
    environment:
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_USER: "postgres"
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "postgres", "-U", "postgres" ]
      timeout: 45s
      interval: 10s
      retries: 10
    volumes:
      - reframe-data-postgresql:/var/lib/postgresql/data
      - ./docker/01-init.sh:/docker-entrypoint-initdb.d/01-init.sh
      - ./docker/init-meta-db.sql:/scripts/init-meta-db.sql

  redis:
    image: redis/redis-stack:latest
    restart: always
    tty: true
#    command: [ "redis-server", "--appendonly", "yes", "--requirepas", "${REDIS_PASSWORD}" ]
    env_file:
      - .env.dev
    environment:
      REDIS_ARGS: "--requirepass reframe --user reframe-user on >reframe ~* allcommands --user default off nopass nocommands"
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping"]
      timeout: 45s
      interval: 10s
      retries: 10
    ports:
      - "48001:8001"
      - "46379:6379"
    volumes:
      - reframe-data-redis:/data


  hasura:
    image: hasura/graphql-engine:v2.30.0
    restart: always
    tty: true
    env_file:
      - .env.dev
    environment:
      # postgres database to store Hasura metadata
      HASURA_GRAPHQL_METADATA_DATABASE_URL: postgres://postgres:postgres@postgres:5432/$HASURA_GRAPHQL_DB_NAME
      ## enable the console served by server
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true" # set to "false" to disable console
      ## enable debugging mode. It is recommended to disable this in production
      HASURA_GRAPHQL_DEV_MODE: "true"
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
      # Unauthorized roles
      HASURA_GRAPHQL_UNAUTHORIZED_ROLE: "anonymous"
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - 48080:8080

  api:
    image: reframeai/api:latest
    restart: always
    tty: true
    command: [ "uvicorn", "reframe.server.main:app", "--host", "0.0.0.0", "--reload"]
    env_file:
      - .env.dev
    healthcheck:
      test: curl --fail http://api:8000/api/v1/system/health/ || exit 1
      interval: 10s
      retries: 10
      start_period: 10s
      timeout: 10s
    ports:
      - 43000:8000
    depends_on:
      postgres:
        condition: service_healthy
      hasura:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - ./:/reframe

  init-workspace:
    image: reframeai/init
    tty: true
    command: bash /02-init-workspace.sh & tail -F maana
    env_file:
      - .env.dev
    volumes:
        - ./docker/02-init-workspace.sh:/02-init-workspace.sh
    depends_on:
      api:
        condition: service_healthy

  app:
    image: reframeai/app:latest
    restart: always
    tty: true
    depends_on:
      api:
        condition: service_healthy
    env_file:
      - .env.dev
    ports:
      - 43001:3000

  agent-browser:
    image: reframeai/engine:latest
    restart: always
    tty: true
    command: [ "nodemon", "--exec", "python3", "reframe/agents/browser/main.py" ]
    depends_on:
      api:
        condition: service_healthy
    env_file:
      - .env.dev
    volumes:
      - ./:/reframe

  agent-serpapi:
    image: reframeai/engine:latest
    restart: always
    tty: true
    command: [ "nodemon", "--exec", "python3", "reframe/agents/serp/main.py" ]
    depends_on:
      api:
        condition: service_healthy
    env_file:
      - .env.dev
    volumes:
      - ./:/reframe

  tool-browser:
    image: reframeai/engine:latest
    restart: always
    tty: true
    command: ["nodemon", "--exec", "python3", "reframe/tools/browser/main.py" ]
    depends_on:
      api:
        condition: service_healthy
    env_file:
      - .env.dev
    deploy:
      mode: replicated
      replicas: 3
    volumes:
      - ./:/reframe

  tool-serpapi:
    image: reframeai/engine:latest
    restart: always
    tty: true
    command: ["nodemon", "--exec", "python3", "reframe/tools/serp/main.py" ]
    depends_on:
      api:
        condition: service_healthy
    env_file:
      - .env.dev
    deploy:
      mode: replicated
      replicas: 3
    volumes:
      - ./:/reframe

volumes:
  reframe-data-postgresql:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /reframe-data/postgresql
  reframe-data-redis:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /reframe-data/redis