# This file extends the base Docker Compose files to make manual testing easy.
#
# Run the following to get started:
#
#     docker compose up -d
#
# That will start up services in the background. To take them down, you have to
# run:
#
#     docker compose down
#
# If you changed DB init scripts, then you should also run:
#
#     docker compose down -v
#
# That'll delete the volumes. Otherwise e.g. PostgreSQL will skip initializing
# if a DB already exists.
#
# If you omit `-d`, it'll run them all in the foreground, then you can stop them
# with your usual Ctrl-C terminal command.
#
# Facts:
#
# * The SERVICE PORTS numbering start at 32123, 32122 etc. to avoid other
#   existing instances of databases.
#
# * The login credentials are, where possible, all "aigent" to avoid unnecessary
#   mental overhead.

version: "3.6"
services:
  postgres:
    extends:
      file: dc-services/postgres.yaml
      service: postgres
    ports:
      - "65002:5432"
    environment:
      POSTGRES_USER: "hasura"
      POSTGRES_PASSWORD: "hasura"
      POSTGRES_DB: "hasura"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./docker-compose/postgres/init.sh:/docker-entrypoint-initdb.d/init-hasura.sh:ro

  dc-reference-agent:
    extends:
      file: dc-agents/docker-compose.yaml
      service: dc-reference-agent

  dc-sqlite-agent:
    extends:
      file: dc-agents/docker-compose.yaml
      service: dc-sqlite-agent

volumes:
  citus-data:
  cockroach-data:
  mssql-data:
  postgres-data: