# This file extends the base Docker Compose files to make manual testing easy.
#
# Run the following to get started:
#
#     docker compose up -d
#
# That will start up services in the background. To take them down, you have to
# run:
#
#     docker compose down
#
# If you changed DB init scripts, then you should also run:
#
#     docker compose down -v
#
# That'll delete the volumes. Otherwise e.g. PostgreSQL will skip initializing
# if a DB already exists.
#
# If you omit `-d`, it'll run them all in the foreground, then you can stop them
# with your usual Ctrl-C terminal command.
#
# Facts:
#
# * The SERVICE PORTS numbering start at 32123, 32122 etc. to avoid other
#   existing instances of databases.
#
# * The login credentials are, where possible, all "aigent" to avoid unnecessary
#   mental overhead.

version: "3.6"
services:
  postgres:
    image: postgres
    restart: always
    ports:
      - "45432:5432"
    environment:
      POSTGRES_USER: "leaptable"
      POSTGRES_PASSWORD: "leaptable"
      POSTGRES_DB: "leaptable"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: