#!/bin/bash
set -e
export PGPASSWORD=$POSTGRES_PASSWORD;
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" <<-EOSQL

  CREATE EXTENSION IF NOT EXISTS moddatetime;

  CREATE USER $REFRAME_DB_USER WITH PASSWORD '$REFRAME_DB_PASS' SUPERUSER;
  ALTER USER $REFRAME_DB_USER CREATEDB;

  CREATE DATABASE "$REFRAME_META_DB_NAME";
  GRANT ALL PRIVILEGES ON DATABASE "$REFRAME_META_DB_NAME" TO $REFRAME_DB_USER;

  CREATE DATABASE "$HASURA_GRAPHQL_DB_NAME";
  GRANT ALL PRIVILEGES ON DATABASE "$HASURA_GRAPHQL_DB_NAME" TO $REFRAME_DB_USER;

EOSQL

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$REFRAME_META_DB_NAME" <<-EOSQL

  GRANT ALL ON SCHEMA public TO $REFRAME_DB_USER;

EOSQL

echo
echo "Initializing Database tables in db '$REFRAME_META_DB_NAME'"
echo
# Create the database tables in the reframe metadb.
PGPASSWORD=$REFRAME_DB_PASS psql -v ON_ERROR_STOP=1 --username "$REFRAME_DB_USER" \
  --dbname "$REFRAME_META_DB_NAME" \
  -f /scripts/init-meta-db.sql